CREATE TABLE PRODUCTS (
	ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_INFO_ID INT(10) NOT NULL,
	SERIAL VARCHAR(50) NOT NULL,
	HASH VARCHAR(128),
	FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO (id)
);
