CREATE TABLE STOCK_MOVEMENTS (
	ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	WAREHOUSE_SOURCE_ID INT(10) NOTwarehouses NULL,
	WAREHOUSE_TARGET_ID INT(10) NOT NULL,
	PRODUCT_ID INT(10) NOT NULL,
	MOVEMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (WAREHOUSE_SOURCE_ID) REFERENCES WAREHOUSES (ID),
	FOREIGN KEY (WAREHOUSE_TARGET_ID) REFERENCES WAREHOUSES (ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);