CREATE TABLE STOCK (
	ID INT (10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	WAREHOUSE_ID INT (10) NOT NULL,
	PRODUCT_INFO_ID INT (10) NOT NULL,
	QUANTITY INT (10) NOT NULL,
	FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (ID),
	FOREIGN KEY (PRODUCT_INFO_ID) REFERENCES PRODUCT_INFO (ID) 
);